### ISSUE TITLE
Figure out what I'm doing with my life

### ISSUE THREAD

**Issue by Ross-CH** [murray55669/iron#1]

**Comment by murray55669** [comment]
I would recommend Meditation. It's free, open source, and many great resources are available online.

Failing that, you could opt for the paid alternative, Hard Drugs. I won't go into that here, but you ought to fully research the pros/cons before diving in.

Finally, if neither of those options work out, the ultimate fallback is Crying Softly combined with Fetal Position. There are deprecated, and have been for roughly 15 years, and are not recommended.
